2024-08-10T20:33:27 {"block_run_id": 137, "block_uuid": "training:LinearSVR", "pipeline_run_id": 34, "pipeline_schedule_id": 3, "pipeline_uuid": "train_sklearn", "hostname": "2f717878a6d7", "block_type": "transformer", "level": "INFO", "message": "Start executing block with BlockExecutor.", "timestamp": 1723322007.372949, "uuid": "79ddf6a32fdd4fcc918f4770b36c6653"}
2024-08-10T20:33:29 {"block_run_id": 137, "block_uuid": "training:LinearSVR", "pipeline_run_id": 34, "pipeline_schedule_id": 3, "pipeline_uuid": "train_sklearn", "hostname": "2f717878a6d7", "block_type": "transformer", "level": "INFO", "message": "2013", "timestamp": 1723322009.178738, "uuid": "43f3e0f48a5040c48e403542b79ce27a"}
2024-08-10T20:33:29 {"block_run_id": 137, "block_uuid": "training:LinearSVR", "pipeline_run_id": 34, "pipeline_schedule_id": 3, "pipeline_uuid": "train_sklearn", "hostname": "2f717878a6d7", "block_type": "transformer", "level": "INFO", "message": "{'epsilon': <hyperopt.pyll.base.Apply object at 0x7f9a50a2c4c0>, 'C': <hyperopt.pyll.base.Apply object at 0x7f9a50a2c5e0>, 'max_iter': <hyperopt.pyll.base.Apply object at 0x7f9a50a2c760>}", "timestamp": 1723322009.179625, "uuid": "bbd0a24b006b4f03b6c7f33eb421f0d7"}
2024-08-10T20:33:29 {"block_run_id": 137, "block_uuid": "training:LinearSVR", "pipeline_run_id": 34, "pipeline_schedule_id": 3, "pipeline_uuid": "train_sklearn", "hostname": "2f717878a6d7", "block_type": "transformer", "level": "INFO", "message": "", "timestamp": 1723322009.186785, "uuid": "c333b8ec876544448d4819b62de8b6d1"}
2024-08-10T20:33:29 {"block_run_id": 137, "block_uuid": "training:LinearSVR", "pipeline_run_id": 34, "pipeline_schedule_id": 3, "pipeline_uuid": "train_sklearn", "hostname": "2f717878a6d7", "block_type": "transformer", "level": "INFO", "message": "  0%|          | 0/50 [00:00<?, ?trial/s, best loss=?]", "timestamp": 1723322009.187091, "uuid": "55365a30bec14bd3a4c339930550ae57"}
2024-08-10T20:33:29 {"block_run_id": 137, "block_uuid": "training:LinearSVR", "pipeline_run_id": 34, "pipeline_schedule_id": 3, "pipeline_uuid": "train_sklearn", "hostname": "2f717878a6d7", "block_type": "transformer", "level": "INFO", "message": "2024/08/10 20:33:29 INFO mlflow.tracking.fluent: Experiment with name 'basketball' does not exist. Creating a new experiment.", "timestamp": 1723322009.831405, "uuid": "7bbae8c7655f499d9a68812df23f73f1"}
2024-08-10T20:33:29 {"block_run_id": 137, "block_uuid": "training:LinearSVR", "pipeline_run_id": 34, "pipeline_schedule_id": 3, "pipeline_uuid": "train_sklearn", "hostname": "2f717878a6d7", "block_type": "transformer", "level": "INFO", "message": "", "timestamp": 1723322009.831893, "uuid": "36b7f909a96342bea939c64ce8c4c1d9"}
2024-08-10T20:33:29 {"block_run_id": 137, "block_uuid": "training:LinearSVR", "pipeline_run_id": 34, "pipeline_schedule_id": 3, "pipeline_uuid": "train_sklearn", "hostname": "2f717878a6d7", "block_type": "transformer", "level": "INFO", "message": "  0%|          | 0/50 [00:00<?, ?trial/s, best loss=?]", "timestamp": 1723322009.832081, "uuid": "f8dfc6571b6744eeb4476f62b10eb6d3"}
2024-08-10T20:33:29 {"block_run_id": 137, "block_uuid": "training:LinearSVR", "pipeline_run_id": 34, "pipeline_schedule_id": 3, "pipeline_uuid": "train_sklearn", "hostname": "2f717878a6d7", "block_type": "transformer", "level": "INFO", "message": "", "timestamp": 1723322009.848595, "uuid": "e78621fb41a34e649746edda21fe3807"}
2024-08-10T20:33:29 {"block_run_id": 137, "block_uuid": "training:LinearSVR", "pipeline_run_id": 34, "pipeline_schedule_id": 3, "pipeline_uuid": "train_sklearn", "hostname": "2f717878a6d7", "block_type": "transformer", "level": "INFO", "message": "  0%|          | 0/50 [00:00<?, ?trial/s, best loss=?]", "timestamp": 1723322009.848842, "uuid": "ea4137170b7c4c7e835127be16f2b511"}
2024-08-10T20:33:29 {"block_run_id": 137, "block_uuid": "training:LinearSVR", "pipeline_run_id": 34, "pipeline_schedule_id": 3, "pipeline_uuid": "train_sklearn", "hostname": "2f717878a6d7", "block_type": "transformer", "level": "WARNING", "message": "Exception thrown when attempting to run <function BlockExecutor.execute.<locals>.__execute_with_retry at 0x7f9a50b9cee0>, attempt 1 of 1", "timestamp": 1723322009.849112, "uuid": "68462fe981054cc99de89bd0ebff659b", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1154, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1685, in execute_sync\n    return __execute()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1662, in __execute\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1564, in __execute\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1904, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2067, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2163, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 33, in hyperparameter_tuning\n  File \"/home/src/Basketball_results_prediction/utils/sklearn.py\", line 138, in tune_hyperparameters\n    best_hyperparameters = fmin(\n  File \"/usr/local/lib/python3.10/site-packages/hyperopt/fmin.py\", line 540, in fmin\n    return trials.fmin(\n  File \"/usr/local/lib/python3.10/site-packages/hyperopt/base.py\", line 671, in fmin\n    return fmin(\n  File \"/usr/local/lib/python3.10/site-packages/hyperopt/fmin.py\", line 586, in fmin\n    rval.exhaust()\n  File \"/usr/local/lib/python3.10/site-packages/hyperopt/fmin.py\", line 364, in exhaust\n    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)\n  File \"/usr/local/lib/python3.10/site-packages/hyperopt/fmin.py\", line 300, in run\n    self.serial_evaluate()\n  File \"/usr/local/lib/python3.10/site-packages/hyperopt/fmin.py\", line 178, in serial_evaluate\n    result = self.domain.evaluate(spec, ctrl)\n  File \"/usr/local/lib/python3.10/site-packages/hyperopt/base.py\", line 892, in evaluate\n    rval = self.fn(pyll_rval)\n  File \"/home/src/Basketball_results_prediction/utils/sklearn.py\", line 93, in __objective\n    mlflow.set_experiment(\"basketball\")\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/tracking/fluent.py\", line 152, in set_experiment\n    experiment_id = client.create_experiment(experiment_name)\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/tracking/client.py\", line 598, in create_experiment\n    return self._tracking_client.create_experiment(name, artifact_location, tags)\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py\", line 254, in create_experiment\n    return self.store.create_experiment(\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py\", line 101, in create_experiment\n    response_proto = self._call_endpoint(CreateExperiment, req_body)\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py\", line 60, in _call_endpoint\n    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/utils/rest_utils.py\", line 290, in call_endpoint\n    response = verify_rest_response(response, endpoint)\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/utils/rest_utils.py\", line 173, in verify_rest_response\n    raise RestException(json.loads(response.text))\nmlflow.exceptions.RestException: RESOURCE_ALREADY_EXISTS: Experiment(name=basketball) already exists. Error: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint \"experiments_name_key\"\nDETAIL:  Key (name)=(basketball) already exists.\n\n[SQL: INSERT INTO experiments (name, artifact_location, lifecycle_stage, creation_time, last_update_time) VALUES (%(name)s, %(artifact_location)s, %(lifecycle_stage)s, %(creation_time)s, %(last_update_time)s) RETURNING experiments.experiment_id]\n[parameters: {'name': 'basketball', 'artifact_location': '', 'lifecycle_stage': 'active', 'creation_time': 1723322009844, 'last_update_time': 1723322009844}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 792, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 106, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 58, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1703, in schedule_all\n    PipelineScheduler(r).start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 198, in start\n    self.schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 334, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 641, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 121, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 198, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 351, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 315, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1236, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 46, in retry_func\n    logger.warning(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 39, in warning\n    self.__send_message('warning', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["RESOURCE_ALREADY_EXISTS: Experiment(name=basketball) already exists. Error: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint \"experiments_name_key\"\nDETAIL:  Key (name)=(basketball) already exists.\n\n[SQL: INSERT INTO experiments (name, artifact_location, lifecycle_stage, creation_time, last_update_time) VALUES (%(name)s, %(artifact_location)s, %(lifecycle_stage)s, %(creation_time)s, %(last_update_time)s) RETURNING experiments.experiment_id]\n[parameters: {'name': 'basketball', 'artifact_location': '', 'lifecycle_stage': 'active', 'creation_time': 1723322009844, 'last_update_time': 1723322009844}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)"]}
2024-08-10T20:33:29 {"block_run_id": 137, "block_uuid": "training:LinearSVR", "pipeline_run_id": 34, "pipeline_schedule_id": 3, "pipeline_uuid": "train_sklearn", "hostname": "2f717878a6d7", "block_type": "transformer", "level": "EXCEPTION", "message": "Failed to execute block training", "timestamp": 1723322009.854611, "uuid": "e761e3e7d4af4c028262232716c4b472", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1154, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1685, in execute_sync\n    return __execute()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1662, in __execute\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1564, in __execute\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1904, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2067, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2163, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 33, in hyperparameter_tuning\n  File \"/home/src/Basketball_results_prediction/utils/sklearn.py\", line 138, in tune_hyperparameters\n    best_hyperparameters = fmin(\n  File \"/usr/local/lib/python3.10/site-packages/hyperopt/fmin.py\", line 540, in fmin\n    return trials.fmin(\n  File \"/usr/local/lib/python3.10/site-packages/hyperopt/base.py\", line 671, in fmin\n    return fmin(\n  File \"/usr/local/lib/python3.10/site-packages/hyperopt/fmin.py\", line 586, in fmin\n    rval.exhaust()\n  File \"/usr/local/lib/python3.10/site-packages/hyperopt/fmin.py\", line 364, in exhaust\n    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)\n  File \"/usr/local/lib/python3.10/site-packages/hyperopt/fmin.py\", line 300, in run\n    self.serial_evaluate()\n  File \"/usr/local/lib/python3.10/site-packages/hyperopt/fmin.py\", line 178, in serial_evaluate\n    result = self.domain.evaluate(spec, ctrl)\n  File \"/usr/local/lib/python3.10/site-packages/hyperopt/base.py\", line 892, in evaluate\n    rval = self.fn(pyll_rval)\n  File \"/home/src/Basketball_results_prediction/utils/sklearn.py\", line 93, in __objective\n    mlflow.set_experiment(\"basketball\")\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/tracking/fluent.py\", line 152, in set_experiment\n    experiment_id = client.create_experiment(experiment_name)\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/tracking/client.py\", line 598, in create_experiment\n    return self._tracking_client.create_experiment(name, artifact_location, tags)\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py\", line 254, in create_experiment\n    return self.store.create_experiment(\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py\", line 101, in create_experiment\n    response_proto = self._call_endpoint(CreateExperiment, req_body)\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py\", line 60, in _call_endpoint\n    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/utils/rest_utils.py\", line 290, in call_endpoint\n    response = verify_rest_response(response, endpoint)\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/utils/rest_utils.py\", line 173, in verify_rest_response\n    raise RestException(json.loads(response.text))\nmlflow.exceptions.RestException: RESOURCE_ALREADY_EXISTS: Experiment(name=basketball) already exists. Error: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint \"experiments_name_key\"\nDETAIL:  Key (name)=(basketball) already exists.\n\n[SQL: INSERT INTO experiments (name, artifact_location, lifecycle_stage, creation_time, last_update_time) VALUES (%(name)s, %(artifact_location)s, %(lifecycle_stage)s, %(creation_time)s, %(last_update_time)s) RETURNING experiments.experiment_id]\n[parameters: {'name': 'basketball', 'artifact_location': '', 'lifecycle_stage': 'active', 'creation_time': 1723322009844, 'last_update_time': 1723322009844}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 792, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 106, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 58, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1703, in schedule_all\n    PipelineScheduler(r).start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 198, in start\n    self.schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 334, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 641, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 121, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 198, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 351, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 315, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1236, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 649, in execute\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["RESOURCE_ALREADY_EXISTS: Experiment(name=basketball) already exists. Error: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint \"experiments_name_key\"\nDETAIL:  Key (name)=(basketball) already exists.\n\n[SQL: INSERT INTO experiments (name, artifact_location, lifecycle_stage, creation_time, last_update_time) VALUES (%(name)s, %(artifact_location)s, %(lifecycle_stage)s, %(creation_time)s, %(last_update_time)s) RETURNING experiments.experiment_id]\n[parameters: {'name': 'basketball', 'artifact_location': '', 'lifecycle_stage': 'active', 'creation_time': 1723322009844, 'last_update_time': 1723322009844}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 647, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 621, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1154, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1685, in execute_sync
    return __execute()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1662, in __execute
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1564, in __execute
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1904, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2067, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2163, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 33, in hyperparameter_tuning
  File "/home/src/Basketball_results_prediction/utils/sklearn.py", line 138, in tune_hyperparameters
    best_hyperparameters = fmin(
  File "/usr/local/lib/python3.10/site-packages/hyperopt/fmin.py", line 540, in fmin
    return trials.fmin(
  File "/usr/local/lib/python3.10/site-packages/hyperopt/base.py", line 671, in fmin
    return fmin(
  File "/usr/local/lib/python3.10/site-packages/hyperopt/fmin.py", line 586, in fmin
    rval.exhaust()
  File "/usr/local/lib/python3.10/site-packages/hyperopt/fmin.py", line 364, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "/usr/local/lib/python3.10/site-packages/hyperopt/fmin.py", line 300, in run
    self.serial_evaluate()
  File "/usr/local/lib/python3.10/site-packages/hyperopt/fmin.py", line 178, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "/usr/local/lib/python3.10/site-packages/hyperopt/base.py", line 892, in evaluate
    rval = self.fn(pyll_rval)
  File "/home/src/Basketball_results_prediction/utils/sklearn.py", line 93, in __objective
    mlflow.set_experiment("basketball")
  File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 152, in set_experiment
    experiment_id = client.create_experiment(experiment_name)
  File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/client.py", line 598, in create_experiment
    return self._tracking_client.create_experiment(name, artifact_location, tags)
  File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 254, in create_experiment
    return self.store.create_experiment(
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 101, in create_experiment
    response_proto = self._call_endpoint(CreateExperiment, req_body)
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 60, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/usr/local/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 290, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/usr/local/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 173, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: RESOURCE_ALREADY_EXISTS: Experiment(name=basketball) already exists. Error: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "experiments_name_key"
DETAIL:  Key (name)=(basketball) already exists.

[SQL: INSERT INTO experiments (name, artifact_location, lifecycle_stage, creation_time, last_update_time) VALUES (%(name)s, %(artifact_location)s, %(lifecycle_stage)s, %(creation_time)s, %(last_update_time)s) RETURNING experiments.experiment_id]
[parameters: {'name': 'basketball', 'artifact_location': '', 'lifecycle_stage': 'active', 'creation_time': 1723322009844, 'last_update_time': 1723322009844}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
