2024-08-03T14:08:37 {"block_run_id": 8, "block_uuid": "prepare_data", "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "get_data_from_bq", "hostname": "ddb6da45c48b", "block_type": "transformer", "level": "INFO", "message": "Start executing block with BlockExecutor.", "timestamp": 1722694117.789432, "uuid": "edc260604b0d44eeb880e68f14192716"}
2024-08-03T14:08:37 {"block_run_id": 8, "block_uuid": "prepare_data", "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "get_data_from_bq", "hostname": "ddb6da45c48b", "block_type": "transformer", "level": "INFO", "message": "--------------------------------------------------------------", "timestamp": 1722694117.928213, "uuid": "e703709ce4224e78bfd2f21bb50dd08b"}
2024-08-03T14:08:37 {"block_run_id": 8, "block_uuid": "prepare_data", "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "get_data_from_bq", "hostname": "ddb6da45c48b", "block_type": "transformer", "level": "INFO", "message": "1/1 tests passed.", "timestamp": 1722694117.928473, "uuid": "cbc720ba93ca461892c484a1788b9ebc"}
2024-08-03T14:08:37 {"block_run_id": 8, "block_uuid": "prepare_data", "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "get_data_from_bq", "hostname": "ddb6da45c48b", "block_type": "transformer", "level": "INFO", "message": "Finish executing block with BlockExecutor.", "timestamp": 1722694117.928749, "uuid": "5635ff08a77b44218d58480ed3a7504d"}
2024-08-03T14:17:37 {"block_run_id": 11, "block_uuid": "prepare_data", "pipeline_run_id": 4, "pipeline_schedule_id": 1, "pipeline_uuid": "get_data_from_bq", "hostname": "ddb6da45c48b", "block_type": "transformer", "level": "INFO", "message": "Start executing block with BlockExecutor.", "timestamp": 1722694657.456285, "uuid": "bec686452a9841a4a2fbba5ed7f0ddb7"}
2024-08-03T14:17:37 {"block_run_id": 11, "block_uuid": "prepare_data", "pipeline_run_id": 4, "pipeline_schedule_id": 1, "pipeline_uuid": "get_data_from_bq", "hostname": "ddb6da45c48b", "block_type": "transformer", "level": "INFO", "message": "--------------------------------------------------------------", "timestamp": 1722694657.589716, "uuid": "3e7468ae8efc43eb9552fd47f05f5f5f"}
2024-08-03T14:17:37 {"block_run_id": 11, "block_uuid": "prepare_data", "pipeline_run_id": 4, "pipeline_schedule_id": 1, "pipeline_uuid": "get_data_from_bq", "hostname": "ddb6da45c48b", "block_type": "transformer", "level": "INFO", "message": "1/1 tests passed.", "timestamp": 1722694657.58996, "uuid": "fbef94e0c0c2446687bd042c86784546"}
2024-08-03T14:17:37 {"block_run_id": 11, "block_uuid": "prepare_data", "pipeline_run_id": 4, "pipeline_schedule_id": 1, "pipeline_uuid": "get_data_from_bq", "hostname": "ddb6da45c48b", "block_type": "transformer", "level": "INFO", "message": "Finish executing block with BlockExecutor.", "timestamp": 1722694657.590247, "uuid": "1ba8716b96af438b90e69f001d189b5d"}
2024-08-04T14:24:14 {"block_run_id": 14, "block_uuid": "prepare_data", "pipeline_run_id": 5, "pipeline_schedule_id": 1, "pipeline_uuid": "get_data_from_bq", "hostname": "ddb6da45c48b", "block_type": "transformer", "level": "INFO", "message": "Start executing block with BlockExecutor.", "timestamp": 1722781454.996417, "uuid": "0d43ee2c1dca4b0486bcd4240a22c402"}
2024-08-04T14:24:15 {"block_run_id": 14, "block_uuid": "prepare_data", "pipeline_run_id": 5, "pipeline_schedule_id": 1, "pipeline_uuid": "get_data_from_bq", "hostname": "ddb6da45c48b", "block_type": "transformer", "level": "WARNING", "message": "Exception thrown when attempting to run <function BlockExecutor.execute.<locals>.__execute_with_retry at 0x7fc47801a7a0>, attempt 1 of 1", "timestamp": 1722781455.068202, "uuid": "831965311643409eb7c0aa0f9dc978d6", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1154, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1675, in execute_sync\n    return __execute()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1652, in __execute\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1554, in __execute\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1894, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2057, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2153, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 32, in transform\nNameError: name 'train_year' is not defined\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 788, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 106, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 58, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1735, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 334, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 641, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 121, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 198, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 351, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 315, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1232, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 46, in retry_func\n    logger.warning(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 39, in warning\n    self.__send_message('warning', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["name 'train_year' is not defined"]}
2024-08-04T14:24:15 {"block_run_id": 14, "block_uuid": "prepare_data", "pipeline_run_id": 5, "pipeline_schedule_id": 1, "pipeline_uuid": "get_data_from_bq", "hostname": "ddb6da45c48b", "block_type": "transformer", "level": "EXCEPTION", "message": "Failed to execute block prepare_data", "timestamp": 1722781455.074149, "uuid": "f75bb39377a54960b02e3695a709d14b", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1154, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1675, in execute_sync\n    return __execute()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1652, in __execute\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1554, in __execute\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1894, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2057, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2153, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 32, in transform\nNameError: name 'train_year' is not defined\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 788, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 106, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 58, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1735, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 334, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 641, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 121, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 198, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 351, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 315, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1232, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 649, in execute\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["name 'train_year' is not defined"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 647, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 621, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1154, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1675, in execute_sync
    return __execute()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1652, in __execute
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1554, in __execute
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1894, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2057, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2153, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 32, in transform
NameError: name 'train_year' is not defined
2024-08-04T14:33:16 {"block_run_id": 17, "block_uuid": "prepare_data", "pipeline_run_id": 6, "pipeline_schedule_id": 1, "pipeline_uuid": "get_data_from_bq", "hostname": "ddb6da45c48b", "block_type": "transformer", "level": "INFO", "message": "Start executing block with BlockExecutor.", "timestamp": 1722781996.500362, "uuid": "599582c1c6044bf1967e3d18a081d453"}
2024-08-04T14:33:16 {"block_run_id": 17, "block_uuid": "prepare_data", "pipeline_run_id": 6, "pipeline_schedule_id": 1, "pipeline_uuid": "get_data_from_bq", "hostname": "ddb6da45c48b", "block_type": "transformer", "level": "INFO", "message": "--------------------------------------------------------------", "timestamp": 1722781996.647905, "uuid": "0e5f4521b2164f8f989e34cf0d46344b"}
2024-08-04T14:33:16 {"block_run_id": 17, "block_uuid": "prepare_data", "pipeline_run_id": 6, "pipeline_schedule_id": 1, "pipeline_uuid": "get_data_from_bq", "hostname": "ddb6da45c48b", "block_type": "transformer", "level": "INFO", "message": "1/1 tests passed.", "timestamp": 1722781996.648152, "uuid": "2d883254f2c34e01b7b33fdc38c89d14"}
2024-08-04T14:33:16 {"block_run_id": 17, "block_uuid": "prepare_data", "pipeline_run_id": 6, "pipeline_schedule_id": 1, "pipeline_uuid": "get_data_from_bq", "hostname": "ddb6da45c48b", "block_type": "transformer", "level": "INFO", "message": "Finish executing block with BlockExecutor.", "timestamp": 1722781996.648434, "uuid": "d9a8fb7631f742b98958126f37e5f2e6"}
2024-08-04T14:33:26 {"block_run_id": 20, "block_uuid": "prepare_data", "pipeline_run_id": 7, "pipeline_schedule_id": 1, "pipeline_uuid": "get_data_from_bq", "hostname": "ddb6da45c48b", "block_type": "transformer", "level": "INFO", "message": "Start executing block with BlockExecutor.", "timestamp": 1722782006.632283, "uuid": "d58db58511e5408e9ce90277c76d0dd7"}
2024-08-04T14:33:26 {"block_run_id": 20, "block_uuid": "prepare_data", "pipeline_run_id": 7, "pipeline_schedule_id": 1, "pipeline_uuid": "get_data_from_bq", "hostname": "ddb6da45c48b", "block_type": "transformer", "level": "INFO", "message": "--------------------------------------------------------------", "timestamp": 1722782006.783078, "uuid": "b3ebe87746874ccd9fce68bb57613c95"}
2024-08-04T14:33:26 {"block_run_id": 20, "block_uuid": "prepare_data", "pipeline_run_id": 7, "pipeline_schedule_id": 1, "pipeline_uuid": "get_data_from_bq", "hostname": "ddb6da45c48b", "block_type": "transformer", "level": "INFO", "message": "1/1 tests passed.", "timestamp": 1722782006.783314, "uuid": "bcd5b4cf70d54a83ba48b343ffa16c73"}
2024-08-04T14:33:26 {"block_run_id": 20, "block_uuid": "prepare_data", "pipeline_run_id": 7, "pipeline_schedule_id": 1, "pipeline_uuid": "get_data_from_bq", "hostname": "ddb6da45c48b", "block_type": "transformer", "level": "INFO", "message": "Finish executing block with BlockExecutor.", "timestamp": 1722782006.783608, "uuid": "9d698f88acb147dc8d37e5303da5c84f"}
2024-08-08T18:58:56 {"block_run_id": 105, "block_uuid": "prepare_data", "pipeline_run_id": 65, "pipeline_schedule_id": 1, "pipeline_uuid": "get_data_from_bq", "hostname": "ddb6da45c48b", "block_type": "transformer", "level": "INFO", "message": "Start executing block with BlockExecutor.", "timestamp": 1723143536.763301, "uuid": "8f0394b33fc94a90a63c15a3b0ba6c82"}
2024-08-08T18:58:56 {"block_run_id": 105, "block_uuid": "prepare_data", "pipeline_run_id": 65, "pipeline_schedule_id": 1, "pipeline_uuid": "get_data_from_bq", "hostname": "ddb6da45c48b", "block_type": "transformer", "level": "INFO", "message": "--------------------------------------------------------------", "timestamp": 1723143536.893823, "uuid": "96de9d34776b4505b6e390037d02c6e6"}
2024-08-08T18:58:56 {"block_run_id": 105, "block_uuid": "prepare_data", "pipeline_run_id": 65, "pipeline_schedule_id": 1, "pipeline_uuid": "get_data_from_bq", "hostname": "ddb6da45c48b", "block_type": "transformer", "level": "INFO", "message": "1/1 tests passed.", "timestamp": 1723143536.894054, "uuid": "b3de3a76d94d4aba85851899816f03af"}
2024-08-08T18:58:56 {"block_run_id": 105, "block_uuid": "prepare_data", "pipeline_run_id": 65, "pipeline_schedule_id": 1, "pipeline_uuid": "get_data_from_bq", "hostname": "ddb6da45c48b", "block_type": "transformer", "level": "INFO", "message": "Finish executing block with BlockExecutor.", "timestamp": 1723143536.89433, "uuid": "061e4528069a47bf889db125b7c96499"}
