2024-08-10T22:38:46 {"cpu": 0.55859375, "cpu_total": 4, "cpu_usage": 0.1396484375, "memory": 2244.0, "memory_total": 16002.0, "memory_usage": 0.14023247094113236, "pipeline_run_id": 49, "pipeline_schedule_id": 3, "pipeline_uuid": "train_sklearn", "hostname": "308e4e76f401", "level": "INFO", "message": "Pipeline train_sklearn for run 49 in schedule 3 is alive.", "timestamp": 1723329526.6359, "uuid": "b03d6eff5a514d9292ce4511dad3826c"}
2024-08-10T22:38:46 {"block_run_id": 236, "block_uuid": "training_set", "pipeline_run_id": 49, "pipeline_schedule_id": 3, "pipeline_uuid": "train_sklearn", "hostname": "308e4e76f401", "level": "INFO", "message": "Execute PipelineRun 49, BlockRun 236: pipeline train_sklearn block training_set", "timestamp": 1723329526.726732, "uuid": "6d08fb77cefb41dba9af9931d9b343f6"}
2024-08-10T22:38:46 {"block_run_id": 237, "block_uuid": "set_models", "pipeline_run_id": 49, "pipeline_schedule_id": 3, "pipeline_uuid": "train_sklearn", "hostname": "308e4e76f401", "level": "INFO", "message": "Execute PipelineRun 49, BlockRun 237: pipeline train_sklearn block set_models", "timestamp": 1723329526.738854, "uuid": "c01b8a49648349debe957520cef11669"}
2024-08-10T22:38:46 {"block_run_id": 237, "block_uuid": "set_models", "pipeline_run_id": 49, "pipeline_schedule_id": 3, "pipeline_uuid": "train_sklearn", "hostname": "308e4e76f401", "level": "INFO", "message": "BlockRun 237 (block_uuid: set_models) completes.", "timestamp": 1723329526.771671, "uuid": "57d5b5a7ac28410d85d5dd42d8c44e4a"}
2024-08-10T22:38:46 {"block_run_id": 236, "block_uuid": "training_set", "pipeline_run_id": 49, "pipeline_schedule_id": 3, "pipeline_uuid": "train_sklearn", "hostname": "308e4e76f401", "level": "INFO", "message": "BlockRun 236 (block_uuid: training_set) completes.", "timestamp": 1723329526.789458, "uuid": "a7155d59079f42518421e434da93d9f8"}
2024-08-10T22:38:47 {"cpu": 0.55859375, "cpu_total": 4, "cpu_usage": 0.1396484375, "memory": 2237.0, "memory_total": 16002.0, "memory_usage": 0.13979502562179727, "pipeline_run_id": 49, "pipeline_schedule_id": 3, "pipeline_uuid": "train_sklearn", "hostname": "308e4e76f401", "level": "INFO", "message": "Pipeline train_sklearn for run 49 in schedule 3 is alive.", "timestamp": 1723329527.138882, "uuid": "7b42bb1c108b48e18f84e26e4498f663"}
2024-08-10T22:38:47 {"block_run_id": 238, "block_uuid": "training", "pipeline_run_id": 49, "pipeline_schedule_id": 3, "pipeline_uuid": "train_sklearn", "hostname": "308e4e76f401", "level": "INFO", "message": "Execute PipelineRun 49, BlockRun 238: pipeline train_sklearn block training", "timestamp": 1723329527.751691, "uuid": "e6529f0c1a2242b686682cb44a6dcd00"}
2024-08-10T22:38:47 {"block_run_id": 238, "block_uuid": "training", "pipeline_run_id": 49, "pipeline_schedule_id": 3, "pipeline_uuid": "train_sklearn", "hostname": "308e4e76f401", "level": "INFO", "message": "BlockRun 238 (block_uuid: training) completes.", "timestamp": 1723329527.811341, "uuid": "8cb7dc5e5c3f4928b2940760a92b232c"}
2024-08-10T22:38:56 {"cpu": 0.5517578125, "cpu_total": 4, "cpu_usage": 0.137939453125, "memory": 2214.0, "memory_total": 16002.0, "memory_usage": 0.13835770528683913, "pipeline_run_id": 49, "pipeline_schedule_id": 3, "pipeline_uuid": "train_sklearn", "hostname": "308e4e76f401", "level": "INFO", "message": "Pipeline train_sklearn for run 49 in schedule 3 is alive.", "timestamp": 1723329536.186462, "uuid": "2b9da51d4338429aadfe1a99c9a6c34d"}
2024-08-10T22:38:56 {"block_run_id": 240, "block_uuid": "training:LinearSVR", "pipeline_run_id": 49, "pipeline_schedule_id": 3, "pipeline_uuid": "train_sklearn", "hostname": "308e4e76f401", "level": "INFO", "message": "Execute PipelineRun 49, BlockRun 240: pipeline train_sklearn block training:LinearSVR", "timestamp": 1723329536.285665, "uuid": "bfce71595a1244d492a90229e5341013"}
2024-08-10T22:38:56 {"block_run_id": 241, "block_uuid": "training:GradientBoostingRegressor", "pipeline_run_id": 49, "pipeline_schedule_id": 3, "pipeline_uuid": "train_sklearn", "hostname": "308e4e76f401", "level": "INFO", "message": "Execute PipelineRun 49, BlockRun 241: pipeline train_sklearn block training:GradientBoostingRegressor", "timestamp": 1723329536.30131, "uuid": "1ba811956a86422f9119295497c73a03"}
2024-08-10T22:38:57 {"block_run_id": 242, "block_uuid": "training:LinearRegression", "pipeline_run_id": 49, "pipeline_schedule_id": 3, "pipeline_uuid": "train_sklearn", "hostname": "308e4e76f401", "level": "INFO", "message": "Execute PipelineRun 49, BlockRun 242: pipeline train_sklearn block training:LinearRegression", "timestamp": 1723329537.353879, "uuid": "cee029385b9b4ce7b05abfa8ed67f560"}
2024-08-10T22:38:57 {"block_run_id": 244, "block_uuid": "training:RandomForestRegressor", "pipeline_run_id": 49, "pipeline_schedule_id": 3, "pipeline_uuid": "train_sklearn", "hostname": "308e4e76f401", "level": "INFO", "message": "Execute PipelineRun 49, BlockRun 244: pipeline train_sklearn block training:RandomForestRegressor", "timestamp": 1723329537.364831, "uuid": "adcd9bbd23544a238ab9eeeaa24f603a"}
2024-08-10T22:38:57 {"block_run_id": 243, "block_uuid": "training:Lasso", "pipeline_run_id": 49, "pipeline_schedule_id": 3, "pipeline_uuid": "train_sklearn", "hostname": "308e4e76f401", "level": "INFO", "message": "Execute PipelineRun 49, BlockRun 243: pipeline train_sklearn block training:Lasso", "timestamp": 1723329537.416487, "uuid": "37993177047e4c5eb6c05b96ccca4cc6"}
2024-08-10T22:38:58 {"block_run_id": 241, "block_uuid": "training:GradientBoostingRegressor", "pipeline_run_id": 49, "pipeline_schedule_id": 3, "pipeline_uuid": "train_sklearn", "hostname": "308e4e76f401", "level": "EXCEPTION", "message": "BlockRun 241 (block_uuid: training:GradientBoostingRegressor) failed.", "timestamp": 1723329538.939194, "uuid": "c25774b169064e91923aa4c85f16cc85", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1154, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1685, in execute_sync\n    return __execute()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1662, in __execute\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1564, in __execute\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1904, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2067, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2163, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 33, in hyperparameter_tuning\n  File \"/home/src/Basketball_results_prediction/utils/sklearn.py\", line 138, in tune_hyperparameters\n    best_hyperparameters = fmin(\n  File \"/usr/local/lib/python3.10/site-packages/hyperopt/fmin.py\", line 540, in fmin\n    return trials.fmin(\n  File \"/usr/local/lib/python3.10/site-packages/hyperopt/base.py\", line 671, in fmin\n    return fmin(\n  File \"/usr/local/lib/python3.10/site-packages/hyperopt/fmin.py\", line 586, in fmin\n    rval.exhaust()\n  File \"/usr/local/lib/python3.10/site-packages/hyperopt/fmin.py\", line 364, in exhaust\n    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)\n  File \"/usr/local/lib/python3.10/site-packages/hyperopt/fmin.py\", line 300, in run\n    self.serial_evaluate()\n  File \"/usr/local/lib/python3.10/site-packages/hyperopt/fmin.py\", line 178, in serial_evaluate\n    result = self.domain.evaluate(spec, ctrl)\n  File \"/usr/local/lib/python3.10/site-packages/hyperopt/base.py\", line 892, in evaluate\n    rval = self.fn(pyll_rval)\n  File \"/home/src/Basketball_results_prediction/utils/sklearn.py\", line 93, in __objective\n    mlflow.set_experiment(\"basketball\")\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/tracking/fluent.py\", line 152, in set_experiment\n    experiment_id = client.create_experiment(experiment_name)\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/tracking/client.py\", line 598, in create_experiment\n    return self._tracking_client.create_experiment(name, artifact_location, tags)\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py\", line 254, in create_experiment\n    return self.store.create_experiment(\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py\", line 101, in create_experiment\n    response_proto = self._call_endpoint(CreateExperiment, req_body)\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py\", line 60, in _call_endpoint\n    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/utils/rest_utils.py\", line 290, in call_endpoint\n    response = verify_rest_response(response, endpoint)\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/utils/rest_utils.py\", line 173, in verify_rest_response\n    raise RestException(json.loads(response.text))\nmlflow.exceptions.RestException: RESOURCE_ALREADY_EXISTS: Experiment(name=basketball) already exists. Error: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint \"experiments_name_key\"\nDETAIL:  Key (name)=(basketball) already exists.\n\n[SQL: INSERT INTO experiments (name, artifact_location, lifecycle_stage, creation_time, last_update_time) VALUES (%(name)s, %(artifact_location)s, %(lifecycle_stage)s, %(creation_time)s, %(last_update_time)s) RETURNING experiments.experiment_id]\n[parameters: {'name': 'basketball', 'artifact_location': '', 'lifecycle_stage': 'active', 'creation_time': 1723329538687, 'last_update_time': 1723329538687}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 792, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 106, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 58, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1731, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 334, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 641, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 121, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 198, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 351, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 315, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1236, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 682, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 465, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["RESOURCE_ALREADY_EXISTS: Experiment(name=basketball) already exists. Error: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint \"experiments_name_key\"\nDETAIL:  Key (name)=(basketball) already exists.\n\n[SQL: INSERT INTO experiments (name, artifact_location, lifecycle_stage, creation_time, last_update_time) VALUES (%(name)s, %(artifact_location)s, %(lifecycle_stage)s, %(creation_time)s, %(last_update_time)s) RETURNING experiments.experiment_id]\n[parameters: {'name': 'basketball', 'artifact_location': '', 'lifecycle_stage': 'active', 'creation_time': 1723329538687, 'last_update_time': 1723329538687}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 647, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 621, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1154, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1685, in execute_sync
    return __execute()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1662, in __execute
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1564, in __execute
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1904, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2067, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2163, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 33, in hyperparameter_tuning
  File "/home/src/Basketball_results_prediction/utils/sklearn.py", line 138, in tune_hyperparameters
    best_hyperparameters = fmin(
  File "/usr/local/lib/python3.10/site-packages/hyperopt/fmin.py", line 540, in fmin
    return trials.fmin(
  File "/usr/local/lib/python3.10/site-packages/hyperopt/base.py", line 671, in fmin
    return fmin(
  File "/usr/local/lib/python3.10/site-packages/hyperopt/fmin.py", line 586, in fmin
    rval.exhaust()
  File "/usr/local/lib/python3.10/site-packages/hyperopt/fmin.py", line 364, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "/usr/local/lib/python3.10/site-packages/hyperopt/fmin.py", line 300, in run
    self.serial_evaluate()
  File "/usr/local/lib/python3.10/site-packages/hyperopt/fmin.py", line 178, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "/usr/local/lib/python3.10/site-packages/hyperopt/base.py", line 892, in evaluate
    rval = self.fn(pyll_rval)
  File "/home/src/Basketball_results_prediction/utils/sklearn.py", line 93, in __objective
    mlflow.set_experiment("basketball")
  File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 152, in set_experiment
    experiment_id = client.create_experiment(experiment_name)
  File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/client.py", line 598, in create_experiment
    return self._tracking_client.create_experiment(name, artifact_location, tags)
  File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 254, in create_experiment
    return self.store.create_experiment(
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 101, in create_experiment
    response_proto = self._call_endpoint(CreateExperiment, req_body)
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 60, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/usr/local/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 290, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/usr/local/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 173, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: RESOURCE_ALREADY_EXISTS: Experiment(name=basketball) already exists. Error: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "experiments_name_key"
DETAIL:  Key (name)=(basketball) already exists.

[SQL: INSERT INTO experiments (name, artifact_location, lifecycle_stage, creation_time, last_update_time) VALUES (%(name)s, %(artifact_location)s, %(lifecycle_stage)s, %(creation_time)s, %(last_update_time)s) RETURNING experiments.experiment_id]
[parameters: {'name': 'basketball', 'artifact_location': '', 'lifecycle_stage': 'active', 'creation_time': 1723329538687, 'last_update_time': 1723329538687}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-08-10T22:39:06 {"cpu": 0.59423828125, "cpu_total": 4, "cpu_usage": 0.1485595703125, "memory": 3349.0, "memory_total": 16002.0, "memory_usage": 0.20928633920759904, "pipeline_run_id": 49, "pipeline_schedule_id": 3, "pipeline_uuid": "train_sklearn", "hostname": "308e4e76f401", "level": "INFO", "message": "Pipeline train_sklearn for run 49 in schedule 3 is alive.", "timestamp": 1723329546.327581, "uuid": "2d4992e6ac974dd5918c2e4242557532"}
