2024-08-10T22:55:47 {"cpu": 0.22705078125, "cpu_total": 4, "cpu_usage": 0.0567626953125, "memory": 2778.0, "memory_total": 16002.0, "memory_usage": 0.17360329958755155, "pipeline_run_id": 52, "pipeline_schedule_id": 1, "pipeline_uuid": "deployment", "hostname": "308e4e76f401", "level": "INFO", "message": "Pipeline deployment for run 52 in schedule 1 is alive.", "timestamp": 1723330547.155903, "uuid": "69e9b16b67144821855473505e94518b"}
2024-08-10T22:55:47 {"cpu": 0.22705078125, "cpu_total": 4, "cpu_usage": 0.0567626953125, "memory": 2803.0, "memory_total": 16002.0, "memory_usage": 0.17516560429946257, "pipeline_run_id": 52, "pipeline_schedule_id": 1, "pipeline_uuid": "deployment", "hostname": "308e4e76f401", "level": "INFO", "message": "Pipeline deployment for run 52 in schedule 1 is alive.", "timestamp": 1723330547.215284, "uuid": "eb706140751e47ba86ac53015c9d6c81"}
2024-08-10T22:55:47 {"block_run_id": 256, "block_uuid": "make_prediction", "pipeline_run_id": 52, "pipeline_schedule_id": 1, "pipeline_uuid": "deployment", "hostname": "308e4e76f401", "level": "INFO", "message": "Execute PipelineRun 52, BlockRun 256: pipeline deployment block make_prediction", "timestamp": 1723330547.237267, "uuid": "f21c0fe0dfcf4bc4aef75611b3a780f9"}
2024-08-10T22:55:57 {"cpu": 0.22412109375, "cpu_total": 4, "cpu_usage": 0.0560302734375, "memory": 2860.0, "memory_total": 16002.0, "memory_usage": 0.17872765904261967, "pipeline_run_id": 52, "pipeline_schedule_id": 1, "pipeline_uuid": "deployment", "hostname": "308e4e76f401", "level": "INFO", "message": "Pipeline deployment for run 52 in schedule 1 is alive.", "timestamp": 1723330557.268902, "uuid": "8dab1b84a74748fd8f275be02321d86d"}
2024-08-10T22:56:02 {"block_run_id": 256, "block_uuid": "make_prediction", "pipeline_run_id": 52, "pipeline_schedule_id": 1, "pipeline_uuid": "deployment", "hostname": "308e4e76f401", "level": "INFO", "message": "BlockRun 256 (block_uuid: make_prediction) completes.", "timestamp": 1723330562.898028, "uuid": "febc730a46d948479bbd96ebb69841bb"}
2024-08-10T22:56:07 {"cpu": 0.22119140625, "cpu_total": 4, "cpu_usage": 0.0552978515625, "memory": 2774.0, "memory_total": 16002.0, "memory_usage": 0.1733533308336458, "pipeline_run_id": 52, "pipeline_schedule_id": 1, "pipeline_uuid": "deployment", "hostname": "308e4e76f401", "level": "INFO", "message": "Pipeline deployment for run 52 in schedule 1 is alive.", "timestamp": 1723330567.311789, "uuid": "e192f033528c4a2fbae7e9346259c2e5"}
2024-08-10T22:56:07 {"block_run_id": 257, "block_uuid": "send_to_monitoring", "pipeline_run_id": 52, "pipeline_schedule_id": 1, "pipeline_uuid": "deployment", "hostname": "308e4e76f401", "level": "INFO", "message": "Execute PipelineRun 52, BlockRun 257: pipeline deployment block send_to_monitoring", "timestamp": 1723330567.390082, "uuid": "26e7165c40854d829d48f900975ff0e3"}
2024-08-10T22:56:07 {"block_run_id": 257, "block_uuid": "send_to_monitoring", "pipeline_run_id": 52, "pipeline_schedule_id": 1, "pipeline_uuid": "deployment", "hostname": "308e4e76f401", "level": "EXCEPTION", "message": "BlockRun 257 (block_uuid: send_to_monitoring) failed.", "timestamp": 1723330567.600037, "uuid": "4e84c4b1bdc940ac8c8528e7b2b74fe0", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1154, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1685, in execute_sync\n    return __execute()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1662, in __execute\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1564, in __execute\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1904, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2035, in _execute_block\n    exec(self.content, results)\n  File \"<string>\", line 7, in <module>\nNameError: name 'List' is not defined\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 792, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 106, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 58, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1731, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 334, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 641, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 121, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 198, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 351, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 315, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1236, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 682, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 465, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["name 'List' is not defined"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 647, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 621, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1154, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1685, in execute_sync
    return __execute()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1662, in __execute
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1564, in __execute
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1904, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2035, in _execute_block
    exec(self.content, results)
  File "<string>", line 7, in <module>
NameError: name 'List' is not defined
2024-08-10T22:56:17 {"cpu": 0.21826171875, "cpu_total": 4, "cpu_usage": 0.0545654296875, "memory": 2773.0, "memory_total": 16002.0, "memory_usage": 0.17329083864516936, "pipeline_run_id": 52, "pipeline_schedule_id": 1, "pipeline_uuid": "deployment", "hostname": "308e4e76f401", "level": "INFO", "message": "Pipeline deployment for run 52 in schedule 1 is alive.", "timestamp": 1723330577.382632, "uuid": "7bc8ed8e7a414fc893541f5cf10e3d47"}
